### ISSUE TITLE
Loading by using multiple processes (to the same graph)

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph-loader#31]
Hi, 

Does HugeGraph Loader is good enough to support be calling in multiple process, to load data into graphs located in the same HugeGraphServer? And, if so, is it a good practice to load simultaneously (by using multiple process) to the same graph?

Thanks!

Best,

**Comment by Linary** [comment]
Thank you very much for your interest in HugeGraph. 

The bottleneck for multi-process execution import is not the HugeGraphLoader, but the HugeGraphServer. Because HugeGraphServer currently only supports stand-alone deployment and its service threads are twice the number of CPU cores, in theory, as long as HugeGraphLoader specifies the same or slightly larger number of threads, the HugeGraphLoader can be fully loaded, so there is no need to use multiple HugeGraphLoader processes. We have not tested this way. If you are interested, you can help us test it. We are happy to receive your feedback.

**Comment by suesunss** [comment]
transaction issue related.
